// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYH2eTGThKQiJqnbAJ8SXDb6LGT3A6g-A',
    appId: '1:688667988918:web:923a35f4e4844818cba717',
    messagingSenderId: '688667988918',
    projectId: 'apcb-e5d60',
    authDomain: 'apcb-e5d60.firebaseapp.com',
    storageBucket: 'apcb-e5d60.appspot.com',
    measurementId: 'G-TJEGK6YYRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqvhGobTLkJFHO17C-Mm3h-mJMVKcAldw',
    appId: '1:688667988918:android:c92a56a64d626dc7cba717',
    messagingSenderId: '688667988918',
    projectId: 'apcb-e5d60',
    storageBucket: 'apcb-e5d60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC88k8WyyyWg6Gg8Uo2eOqcCpFodbhzHro',
    appId: '1:688667988918:ios:509cf6aa556b8a9ecba717',
    messagingSenderId: '688667988918',
    projectId: 'apcb-e5d60',
    storageBucket: 'apcb-e5d60.appspot.com',
    iosBundleId: 'com.example.apb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC88k8WyyyWg6Gg8Uo2eOqcCpFodbhzHro',
    appId: '1:688667988918:ios:509cf6aa556b8a9ecba717',
    messagingSenderId: '688667988918',
    projectId: 'apcb-e5d60',
    storageBucket: 'apcb-e5d60.appspot.com',
    iosBundleId: 'com.example.apb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYH2eTGThKQiJqnbAJ8SXDb6LGT3A6g-A',
    appId: '1:688667988918:web:8c65a9f3cd248c17cba717',
    messagingSenderId: '688667988918',
    projectId: 'apcb-e5d60',
    authDomain: 'apcb-e5d60.firebaseapp.com',
    storageBucket: 'apcb-e5d60.appspot.com',
    measurementId: 'G-Z9GQVZN3HM',
  );

}